server.port: ${service_port:3001}
spring:
  application.name: member
  profiles.active: dev
  
ottmember:
  filepath: ${ottmember_filepath:data/members.properties}
  authtoken: ${ottmember_authtoken:P@ssword!}

logging.level:
  root: INFO
  org.springframework.web: ERROR
